import catalogJson from '../data/mitre/enterprise-attack.json' with { type: 'json' };

// Static MITRE ATT&CK Enterprise reference data (regenerated by scripts/build-mitre-catalog.mjs, then
// committed). Deliberately a file, not a table: read-only, versioned in git, and outside the CONFIG/RUN
// reset model entirely. Stored technique ids stay valid across upgrades — one that a newer catalog
// drops just renders as unknown instead of breaking anything.
export interface MitreTactic {
  id: string;
  shortname: string;
  name: string;
  order: number;
}

export interface MitreTechnique {
  id: string;
  name: string;
  tacticIds: string[];
  parentId: string | null;
}

export interface MitreCatalog {
  attackVersion: string;
  tactics: MitreTactic[];
  techniques: MitreTechnique[];
}

const catalog: MitreCatalog = {
  attackVersion: catalogJson.attackVersion,
  tactics: catalogJson.tactics,
  techniques: catalogJson.techniques,
};

const techniqueById = new Map(catalog.techniques.map((t) => [t.id, t]));
const tacticById = new Map(catalog.tactics.map((t) => [t.id, t]));

export function listCatalog(): MitreCatalog {
  return catalog;
}

export function getTechnique(id: string): MitreTechnique | undefined {
  return techniqueById.get(id);
}

export function getTactic(id: string): MitreTactic | undefined {
  return tacticById.get(id);
}

export function isValidTechniqueId(id: unknown): id is string {
  return typeof id === 'string' && techniqueById.has(id);
}

// "T1087.001 — Local Account" style label for score notes; a sub-technique carries its parent's name
// too since "Local Account" alone is meaningless out of context.
export function techniqueLabel(id: string): string {
  const technique = techniqueById.get(id);
  if (!technique) return `${id} — unknown technique`;
  const parent = technique.parentId ? techniqueById.get(technique.parentId) : undefined;
  return `${id} — ${parent ? `${parent.name}: ` : ''}${technique.name}`;
}
